# SERVER PORT 설정
server:
  port: 8080


# SPRING NAME
spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?currentSchema=public
    username: postgres.ftoqewhpbrypaeclukso
    password: mintHouse1234@@
    driver-class-name: org.postgresql.Driver
  application:
    name: cshmint
  messages:
    basename: messages
    encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health

#logging
logging:
  level:
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.zaxxer.hikari: debug
    org.mybatis: debug

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.cshbk.cshmint
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#JWT
jwt:
  secret: "my-super-secret-key-my-super-secret-key-123456"
  expiration: 3600000 # 1시간