# SERVER PORT 설정
server:
  port: 8080


# SPRING NAME
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/srcshbk
    username: srhan
    password: srhan@0310
    driver-class-name: org.postgresql.Driver
  application:
    name: cshmint
  messages:
    basename: messages
    encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.cshbk.cshmint
  configuration:
    map-underscore-to-camel-case: true